/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.infox.telas;
import java.sql.*;
import br.com.infox.dal.ModuloConexao;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author jaque
 */
public class TelaPesquisaUsuario extends javax.swing.JInternalFrame {

    
    Connection conexao = null;
PreparedStatement pst = null;
ResultSet rs = null;

// Método para pesquisar usuários pelo nome
private void pesquisarUsuario() {
    String sql = "SELECT iduser, usuario, login FROM tbusuarios WHERE usuario LIKE ?";
    try {
        // Conectar ao banco de dados
        conexao = ModuloConexao.conector();
        pst = conexao.prepareStatement(sql);
        // Usar o texto digitado no campo de pesquisa para filtrar os resultados
        pst.setString(1, "%" + txtUsuPesquisar.getText() + "%");
        rs = pst.executeQuery();

        // Configurar o modelo da tabela
        DefaultTableModel modelo = (DefaultTableModel) tblUsuarios.getModel();
        modelo.setRowCount(0); // Limpar a tabela antes de adicionar novos resultados

        // Preencher a tabela com os resultados da pesquisa
        while (rs.next()) {
            Object[] row = {
                rs.getInt("iduser"),
                rs.getString("usuario"),
                rs.getString("login")
            };
            modelo.addRow(row);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao pesquisar usuários: " + e);
    } finally {
        // Fechar a conexão com o banco de dados
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
            if (conexao != null) conexao.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
    /**
     * Creates new form TelaPesquisaUsuario
     */
    public TelaPesquisaUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        txtUsuPesquisar = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Pesquisar Usuários");

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nome", "Usuário"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblUsuarios);

        txtUsuPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuPesquisarActionPerformed(evt);
            }
        });
        txtUsuPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuPesquisarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                    .addComponent(txtUsuPesquisar))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(txtUsuPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        // TODO add your handling code here:
         int selecionado = tblUsuarios.getSelectedRow();
    if (selecionado != -1) {
        String id = tblUsuarios.getValueAt(selecionado, 0).toString();
        String nome = tblUsuarios.getValueAt(selecionado, 1).toString();
        String login = tblUsuarios.getValueAt(selecionado, 2).toString();
        
        // Exemplo: Mostrar o nome em uma caixa de diálogo (ou use em outro campo)
        JOptionPane.showMessageDialog(null, "Usuário selecionado: " + nome);
    }

    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void txtUsuPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuPesquisarActionPerformed

    private void txtUsuPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuPesquisarKeyReleased
        // TODO add your handling code here:
            pesquisarUsuario();


    }//GEN-LAST:event_txtUsuPesquisarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtUsuPesquisar;
    // End of variables declaration//GEN-END:variables

    void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
