/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.infox.telas;

import javax.swing.JOptionPane;

/**
 *
 * @author jaque
 */
public class TelaCalculadora extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCalculadora
     */
    public TelaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextResultado = new javax.swing.JTextArea();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        btnSomar = new javax.swing.JButton();
        btnSubtrair = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("CALCULADORA");

        jTextResultado.setColumns(20);
        jTextResultado.setRows(5);
        jScrollPane1.setViewportView(jTextResultado);

        btnSomar.setText("Somar +");
        btnSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomarActionPerformed(evt);
            }
        });

        btnSubtrair.setText("Subtrair -");
        btnSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtrairActionPerformed(evt);
            }
        });

        btnMultiplicar.setText("Multiplicar x");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });

        btnDividir.setText("Dividir ÷");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSomar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubtrair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMultiplicar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDividir)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomarActionPerformed
       try {
        // Captura os valores dos campos de texto e substitui a vírgula por ponto
        double num1 = Double.parseDouble(txt1.getText().replace(',', '.'));
        double num2 = Double.parseDouble(txt2.getText().replace(',', '.'));

        // Soma os dois números
        double resultado = num1 + num2;

        // Exibe o resultado no campo jTextResultado com 2 casas decimais
        jTextResultado.setText("Resultado: " + String.format("%.2f", resultado));
    } catch (NumberFormatException e) {
        // Exibe uma mensagem de erro se os valores não forem números válidos
        JOptionPane.showMessageDialog(this, "Por favor, insira números válidos.");
    }
        
    }//GEN-LAST:event_btnSomarActionPerformed

    private void btnSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtrairActionPerformed
        // TODO add your handling code here:
          try {
        // Captura os valores dos campos de texto e substitui a vírgula por ponto
        double num1 = Double.parseDouble(txt1.getText().replace(',', '.'));
        double num2 = Double.parseDouble(txt2.getText().replace(',', '.'));

        // Subtrai os dois números
        double resultado = num1 - num2;

        // Exibe o resultado no campo jTextResultado com 2 casas decimais
        jTextResultado.setText("Resultado: " + String.format("%.2f", resultado));
    } catch (NumberFormatException e) {
        // Exibe uma mensagem de erro se os valores não forem números válidos
        JOptionPane.showMessageDialog(this, "Por favor, insira números válidos.");
    }
        
        
    }//GEN-LAST:event_btnSubtrairActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        // TODO add your handling code here:
          try {
        // Captura os valores dos campos de texto e substitui a vírgula por ponto
        double num1 = Double.parseDouble(txt1.getText().replace(',', '.'));
        double num2 = Double.parseDouble(txt2.getText().replace(',', '.'));

        // Multiplica os dois números
        double resultado = num1 * num2;

        // Exibe o resultado no campo jTextResultado com 2 casas decimais
        jTextResultado.setText("Resultado: " + String.format("%.2f", resultado));
    } catch (NumberFormatException e) {
        // Exibe uma mensagem de erro se os valores não forem números válidos
        JOptionPane.showMessageDialog(this, "Por favor, insira números válidos.");
    }
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        // TODO add your handling code here:
        try {
        // Captura os valores dos campos de texto e substitui a vírgula por ponto
        double num1 = Double.parseDouble(txt1.getText().replace(',', '.'));
        double num2 = Double.parseDouble(txt2.getText().replace(',', '.'));

        // Verifica se o divisor (num2) não é zero
        if (num2 == 0) {
            JOptionPane.showMessageDialog(this, "Não é possível dividir por zero.");
        } else {
            // Realiza a divisão
            double resultado = num1 / num2;

            // Exibe o resultado no campo jTextResultado com 2 casas decimais
            jTextResultado.setText("Resultado: " + String.format("%.2f", resultado));
        }
    } catch (NumberFormatException e) {
        // Exibe uma mensagem de erro se os valores não forem números válidos
        JOptionPane.showMessageDialog(this, "Por favor, insira números válidos.");
    }
        
        
    }//GEN-LAST:event_btnDividirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnSomar;
    private javax.swing.JButton btnSubtrair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextResultado;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
